{% set name = "gazebo_robotraconteur_server_plugin" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #git_url: https://github.com/robotraconteur-contrib/RobotRaconteur_Gazebo_Server_Plugin.git
  #git_rev: v{{ version }}
  # Use tarball
  url: https://github.com/robotraconteur-contrib/RobotRaconteur_Gazebo_Server_Plugin/archive/v{{ version }}.tar.gz
  sha256: ae75e9f849522d02bdee77d8eea48d4b6cb9056646ea26458f54a08614dfb06f

build:
  number: 7


requirements:
  build:
    - git
    - cmake
    - make  # [linux]
    - ninja  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - robotraconteur >=0.18.0
    - robotraconteur_companion >=0.3.1
    - gazebo
    - libboost-devel
    - yaml-cpp
    - eigen
    - pkgconfig
  run:
    - robotraconteur >=0.18.0
    - robotraconteur_companion >=0.3.1
    - gazebo
    - yaml-cpp
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

about:
  home: https://github.com/robotraconteur-contrib/RobotRaconteur_Gazebo_Server_Plugin
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Robot Raconteur plugin for the Gazebo Robot Simulator'

extra:
  recipe-maintainers:
    - johnwason
