package:
  name: gazebo_robotraconteur_server_plugin
  version: 0.2.0

source:
  git_url: https://github.com/robotraconteur-contrib/RobotRaconteur_Gazebo_Server_Plugin.git
  git_depth: 1

requirements:
  host:
    - robotraconteur >=0.16.0
    - robotraconteur_companion >=0.2.0
    - gazebo
    - git
    - cmake
    - boost-cpp
    - make # [linux]
    - ninja # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - yaml-cpp
    - eigen
    - pkgconfig
  run:
    - boost-cpp
    - robotraconteur >=0.16.0
    - robotraconteur_companion >=0.2.0
    - gazebo
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

build:
  number: 1

about:
  home: https://github.com/robotraconteur-contrib/RobotRaconteur_Gazebo_Server_Plugin
  license: Apache 2.0
  summary: 'Robot Raconteur plugin for the Gazebo Robot Simulator'